// GENERATED — do not edit. Source: third_party/lw_abi (pinned LW_ABI_VERSION).
// ignore_for_file: type=lint, unused_field, unused_element, camel_case_types

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Raw FFI bindings to the libwebrtc flat C ABI (lw_*). Internal.
class LwBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LwBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LwBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Returns the ABI version the loaded library was built against. A caller
  /// compares this to its own LW_ABI_VERSION at load time.
  int lw_abi_version() {
    return _lw_abi_version();
  }

  late final _lw_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('lw_abi_version');
  late final _lw_abi_version = _lw_abi_versionPtr.asFunction<int Function()>();

  /// Global init/teardown. lw_initialize returns nonzero on success and must be
  /// called once before creating a factory; lw_terminate is called after all
  /// handles have been released. Both are thread-safe.
  int lw_initialize() {
    return _lw_initialize();
  }

  late final _lw_initializePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('lw_initialize');
  late final _lw_initialize = _lw_initializePtr.asFunction<int Function()>();

  void lw_terminate() {
    return _lw_terminate();
  }

  late final _lw_terminatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('lw_terminate');
  late final _lw_terminate = _lw_terminatePtr.asFunction<void Function()>();

  /// Creates a peer-connection factory. Returns NULL on failure; the handle owns
  /// one reference (retire it with lw_release). Call lw_factory_initialize before
  /// using it.
  ffi.Pointer<lw_factory_t> lw_factory_create() {
    return _lw_factory_create();
  }

  late final _lw_factory_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<lw_factory_t> Function()>>(
          'lw_factory_create');
  late final _lw_factory_create =
      _lw_factory_createPtr.asFunction<ffi.Pointer<lw_factory_t> Function()>();

  /// Initializes a factory. Returns nonzero on success.
  int lw_factory_initialize(
    ffi.Pointer<lw_factory_t> factory1,
  ) {
    return _lw_factory_initialize(
      factory1,
    );
  }

  late final _lw_factory_initializePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<lw_factory_t>)>>(
          'lw_factory_initialize');
  late final _lw_factory_initialize = _lw_factory_initializePtr
      .asFunction<int Function(ffi.Pointer<lw_factory_t>)>();

  /// Retain/release any lw_* handle (all map to the shared RefCountInterface).
  /// One pair covers every handle type. Null handles are ignored. Handles may be
  /// released in any order: each keeps the factory it came from alive.
  void lw_retain(
    ffi.Pointer<ffi.Void> handle,
  ) {
    return _lw_retain(
      handle,
    );
  }

  late final _lw_retainPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'lw_retain');
  late final _lw_retain =
      _lw_retainPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void lw_release(
    ffi.Pointer<ffi.Void> handle,
  ) {
    return _lw_release(
      handle,
    );
  }

  late final _lw_releasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'lw_release');
  late final _lw_release =
      _lw_releasePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// Frees a payload delivered to a callback below. Every `char*` a callback
  /// receives is owned by the callback, which passes it here once done. NULL is
  /// ignored.
  ///
  /// Data channel messages come this way too. They are length-delimited, since a
  /// binary message may contain zero bytes, but a NUL is appended past the length
  /// so a text message can also be read as a C string.
  void lw_string_free(
    ffi.Pointer<ffi.Char> s,
  ) {
    return _lw_string_free(
      s,
    );
  }

  late final _lw_string_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
          'lw_string_free');
  late final _lw_string_free =
      _lw_string_freePtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Registers a native video sink. `sink` and `user` are caller-owned and MUST
  /// outlive the binding (they are referenced, not copied). Returns an
  /// unguessable token, or 0 on failure (null/invalid sink).
  int lw_video_sink_register(
    ffi.Pointer<LwVideoSinkV1> sink,
    ffi.Pointer<ffi.Void> user,
  ) {
    return _lw_video_sink_register(
      sink,
      user,
    );
  }

  late final _lw_video_sink_registerPtr = _lookup<
      ffi.NativeFunction<
          lw_video_sink_token Function(ffi.Pointer<LwVideoSinkV1>,
              ffi.Pointer<ffi.Void>)>>('lw_video_sink_register');
  late final _lw_video_sink_register = _lw_video_sink_registerPtr.asFunction<
      int Function(ffi.Pointer<LwVideoSinkV1>, ffi.Pointer<ffi.Void>)>();

  /// Unregisters a sink token. Returns 0 on success, negative if unknown. Does
  /// not unbind: unbind the track first (lw_video_track_unbind_sink).
  int lw_video_sink_unregister(
    int token,
  ) {
    return _lw_video_sink_unregister(
      token,
    );
  }

  late final _lw_video_sink_unregisterPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(lw_video_sink_token)>>(
          'lw_video_sink_unregister');
  late final _lw_video_sink_unregister =
      _lw_video_sink_unregisterPtr.asFunction<int Function(int)>();

  /// Binds a registered sink to a video track; native frames on the track are
  /// then delivered to the sink. Returns 0 on success, negative on error
  /// (null/unknown track, unknown token).
  int lw_video_track_bind_sink(
    ffi.Pointer<lw_video_track_t> track,
    int token,
  ) {
    return _lw_video_track_bind_sink(
      track,
      token,
    );
  }

  late final _lw_video_track_bind_sinkPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<lw_video_track_t>,
              lw_video_sink_token)>>('lw_video_track_bind_sink');
  late final _lw_video_track_bind_sink = _lw_video_track_bind_sinkPtr
      .asFunction<int Function(ffi.Pointer<lw_video_track_t>, int)>();

  /// Unbinds any native sink from a track. Quiesces: blocks until an in-flight
  /// on_frame returns, and emits on_eos to the previously-bound sink. Returns 0
  /// on success, negative on error.
  int lw_video_track_unbind_sink(
    ffi.Pointer<lw_video_track_t> track,
  ) {
    return _lw_video_track_unbind_sink(
      track,
    );
  }

  late final _lw_video_track_unbind_sinkPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<lw_video_track_t>)>>(
      'lw_video_track_unbind_sink');
  late final _lw_video_track_unbind_sink = _lw_video_track_unbind_sinkPtr
      .asFunction<int Function(ffi.Pointer<lw_video_track_t>)>();

  int lw_video_track_set_frame_callback(
    ffi.Pointer<lw_video_track_t> track,
    lw_frame_cb cb,
    ffi.Pointer<ffi.Void> user,
  ) {
    return _lw_video_track_set_frame_callback(
      track,
      cb,
      user,
    );
  }

  late final _lw_video_track_set_frame_callbackPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<lw_video_track_t>, lw_frame_cb,
              ffi.Pointer<ffi.Void>)>>('lw_video_track_set_frame_callback');
  late final _lw_video_track_set_frame_callback =
      _lw_video_track_set_frame_callbackPtr.asFunction<
          int Function(ffi.Pointer<lw_video_track_t>, lw_frame_cb,
              ffi.Pointer<ffi.Void>)>();

  /// Creates a peer connection on `factory` with a default configuration.
  /// Returns NULL on failure; the handle owns one reference (lw_release).
  ffi.Pointer<lw_pc_t> lw_pc_create(
    ffi.Pointer<lw_factory_t> factory1,
  ) {
    return _lw_pc_create(
      factory1,
    );
  }

  late final _lw_pc_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<lw_pc_t> Function(
              ffi.Pointer<lw_factory_t>)>>('lw_pc_create');
  late final _lw_pc_create = _lw_pc_createPtr
      .asFunction<ffi.Pointer<lw_pc_t> Function(ffi.Pointer<lw_factory_t>)>();

  /// Closes a peer connection. The handle stays valid until lw_release.
  void lw_pc_close(
    ffi.Pointer<lw_pc_t> pc,
  ) {
    return _lw_pc_close(
      pc,
    );
  }

  late final _lw_pc_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<lw_pc_t>)>>(
          'lw_pc_close');
  late final _lw_pc_close =
      _lw_pc_closePtr.asFunction<void Function(ffi.Pointer<lw_pc_t>)>();

  /// Adds a transceiver of `media_type` (default direction). Returns NULL on
  /// failure; the handle owns one reference.
  ffi.Pointer<lw_transceiver_t> lw_pc_add_transceiver(
    ffi.Pointer<lw_pc_t> pc,
    lw_media_type media_type,
  ) {
    return _lw_pc_add_transceiver(
      pc,
      media_type.value,
    );
  }

  late final _lw_pc_add_transceiverPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<lw_transceiver_t> Function(
              ffi.Pointer<lw_pc_t>, ffi.UnsignedInt)>>('lw_pc_add_transceiver');
  late final _lw_pc_add_transceiver = _lw_pc_add_transceiverPtr.asFunction<
      ffi.Pointer<lw_transceiver_t> Function(ffi.Pointer<lw_pc_t>, int)>();

  /// Returns the transceiver's receiver, or NULL. Handle owns one reference.
  ffi.Pointer<lw_receiver_t> lw_transceiver_receiver(
    ffi.Pointer<lw_transceiver_t> transceiver,
  ) {
    return _lw_transceiver_receiver(
      transceiver,
    );
  }

  late final _lw_transceiver_receiverPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<lw_receiver_t> Function(
              ffi.Pointer<lw_transceiver_t>)>>('lw_transceiver_receiver');
  late final _lw_transceiver_receiver = _lw_transceiver_receiverPtr.asFunction<
      ffi.Pointer<lw_receiver_t> Function(ffi.Pointer<lw_transceiver_t>)>();

  /// Returns the receiver's video track as a handle bindable with
  /// lw_video_track_bind_sink, or NULL if the receiver has no video track. Handle
  /// owns one reference.
  ffi.Pointer<lw_video_track_t> lw_receiver_video_track(
    ffi.Pointer<lw_receiver_t> receiver,
  ) {
    return _lw_receiver_video_track(
      receiver,
    );
  }

  late final _lw_receiver_video_trackPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<lw_video_track_t> Function(
              ffi.Pointer<lw_receiver_t>)>>('lw_receiver_video_track');
  late final _lw_receiver_video_track = _lw_receiver_video_trackPtr.asFunction<
      ffi.Pointer<lw_video_track_t> Function(ffi.Pointer<lw_receiver_t>)>();

  /// Creates a video source that frames are pushed into, rather than one driven
  /// by a capture device. `label` is a diagnostic name and may be NULL. Returns
  /// NULL on failure; the handle owns one reference.
  ffi.Pointer<lw_video_source_t> lw_factory_create_video_source(
    ffi.Pointer<lw_factory_t> factory1,
    ffi.Pointer<ffi.Char> label,
  ) {
    return _lw_factory_create_video_source(
      factory1,
      label,
    );
  }

  late final _lw_factory_create_video_sourcePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<lw_video_source_t> Function(ffi.Pointer<lw_factory_t>,
              ffi.Pointer<ffi.Char>)>>('lw_factory_create_video_source');
  late final _lw_factory_create_video_source =
      _lw_factory_create_video_sourcePtr.asFunction<
          ffi.Pointer<lw_video_source_t> Function(
              ffi.Pointer<lw_factory_t>, ffi.Pointer<ffi.Char>)>();

  /// Pushes one I420 frame into a source. `data` holds width*height*3/2 bytes:
  /// the Y plane, then U, then V, each tightly packed. The data is copied, so it
  /// need not outlive the call. Returns 0 on success, negative on error (null
  /// handle, bad dimensions, or a size that does not match them).
  ///
  /// Frames are consumed at whatever rate they are pushed; the caller sets the
  /// pace.
  int lw_video_source_push_i420(
    ffi.Pointer<lw_video_source_t> source,
    int width,
    int height,
    ffi.Pointer<ffi.Uint8> data,
    int size,
  ) {
    return _lw_video_source_push_i420(
      source,
      width,
      height,
      data,
      size,
    );
  }

  late final _lw_video_source_push_i420Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<lw_video_source_t>, ffi.Int, ffi.Int,
              ffi.Pointer<ffi.Uint8>, ffi.Size)>>('lw_video_source_push_i420');
  late final _lw_video_source_push_i420 =
      _lw_video_source_push_i420Ptr.asFunction<
          int Function(ffi.Pointer<lw_video_source_t>, int, int,
              ffi.Pointer<ffi.Uint8>, int)>();

  /// Creates a local video track fed by `source`.
  ///
  /// `id` becomes the track's id in the SDP and must be a non-empty string: an
  /// empty one produces an "a=msid:<stream> " line with nothing after the space,
  /// which the far side rejects when parsing the session description. That
  /// failure names the msid attribute and says nothing about the track, so it is
  /// refused here instead. Returns NULL on failure; the handle owns one
  /// reference.
  ffi.Pointer<lw_video_track_t> lw_factory_create_video_track(
    ffi.Pointer<lw_factory_t> factory1,
    ffi.Pointer<lw_video_source_t> source,
    ffi.Pointer<ffi.Char> id,
  ) {
    return _lw_factory_create_video_track(
      factory1,
      source,
      id,
    );
  }

  late final _lw_factory_create_video_trackPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<lw_video_track_t> Function(
              ffi.Pointer<lw_factory_t>,
              ffi.Pointer<lw_video_source_t>,
              ffi.Pointer<ffi.Char>)>>('lw_factory_create_video_track');
  late final _lw_factory_create_video_track =
      _lw_factory_create_video_trackPtr.asFunction<
          ffi.Pointer<lw_video_track_t> Function(ffi.Pointer<lw_factory_t>,
              ffi.Pointer<lw_video_source_t>, ffi.Pointer<ffi.Char>)>();

  /// Attaches a local track to a peer connection, in the streams named by
  /// `stream_ids` (may be NULL when `stream_id_count` is 0). Returns the sender,
  /// or NULL on failure; the handle owns one reference.
  ffi.Pointer<lw_sender_t> lw_pc_add_track(
    ffi.Pointer<lw_pc_t> pc,
    ffi.Pointer<lw_video_track_t> track,
    ffi.Pointer<ffi.Pointer<ffi.Char>> stream_ids,
    int stream_id_count,
  ) {
    return _lw_pc_add_track(
      pc,
      track,
      stream_ids,
      stream_id_count,
    );
  }

  late final _lw_pc_add_trackPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<lw_sender_t> Function(
              ffi.Pointer<lw_pc_t>,
              ffi.Pointer<lw_video_track_t>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
              ffi.Size)>>('lw_pc_add_track');
  late final _lw_pc_add_track = _lw_pc_add_trackPtr.asFunction<
      ffi.Pointer<lw_sender_t> Function(
          ffi.Pointer<lw_pc_t>,
          ffi.Pointer<lw_video_track_t>,
          ffi.Pointer<ffi.Pointer<ffi.Char>>,
          int)>();

  /// Enables or disables a track. A disabled track still flows, but carries
  /// black frames -- this is mute, not removal. Works on local and remote tracks
  /// alike. Returns 0 on success, negative on error.
  int lw_video_track_set_enabled(
    ffi.Pointer<lw_video_track_t> track,
    int enabled,
  ) {
    return _lw_video_track_set_enabled(
      track,
      enabled,
    );
  }

  late final _lw_video_track_set_enabledPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<lw_video_track_t>,
              ffi.Int)>>('lw_video_track_set_enabled');
  late final _lw_video_track_set_enabled = _lw_video_track_set_enabledPtr
      .asFunction<int Function(ffi.Pointer<lw_video_track_t>, int)>();

  /// Whether a track is enabled. Returns 1, 0, or negative on error.
  int lw_video_track_enabled(
    ffi.Pointer<lw_video_track_t> track,
  ) {
    return _lw_video_track_enabled(
      track,
    );
  }

  late final _lw_video_track_enabledPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<lw_video_track_t>)>>(
      'lw_video_track_enabled');
  late final _lw_video_track_enabled = _lw_video_track_enabledPtr
      .asFunction<int Function(ffi.Pointer<lw_video_track_t>)>();

  /// Fills `out` with the track's counters. `out->size` must be set by the caller
  /// to sizeof(LwVideoTrackStats) before the call. Returns 0 on success, negative
  /// on error (null or non-video track, missing or mismatched size).
  int lw_video_track_get_stats(
    ffi.Pointer<lw_video_track_t> track,
    ffi.Pointer<LwVideoTrackStats> out,
  ) {
    return _lw_video_track_get_stats(
      track,
      out,
    );
  }

  late final _lw_video_track_get_statsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<lw_video_track_t>,
              ffi.Pointer<LwVideoTrackStats>)>>('lw_video_track_get_stats');
  late final _lw_video_track_get_stats =
      _lw_video_track_get_statsPtr.asFunction<
          int Function(
              ffi.Pointer<lw_video_track_t>, ffi.Pointer<LwVideoTrackStats>)>();

  /// Creates an offer/answer. On success `on_success` receives the SDP and its
  /// type ("offer"/"answer").
  void lw_pc_create_offer(
    ffi.Pointer<lw_pc_t> pc,
    lw_sdp_success_cb on_success,
    lw_sdp_failure_cb on_failure,
    ffi.Pointer<ffi.Void> user,
  ) {
    return _lw_pc_create_offer(
      pc,
      on_success,
      on_failure,
      user,
    );
  }

  late final _lw_pc_create_offerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<lw_pc_t>, lw_sdp_success_cb,
              lw_sdp_failure_cb, ffi.Pointer<ffi.Void>)>>('lw_pc_create_offer');
  late final _lw_pc_create_offer = _lw_pc_create_offerPtr.asFunction<
      void Function(ffi.Pointer<lw_pc_t>, lw_sdp_success_cb, lw_sdp_failure_cb,
          ffi.Pointer<ffi.Void>)>();

  void lw_pc_create_answer(
    ffi.Pointer<lw_pc_t> pc,
    lw_sdp_success_cb on_success,
    lw_sdp_failure_cb on_failure,
    ffi.Pointer<ffi.Void> user,
  ) {
    return _lw_pc_create_answer(
      pc,
      on_success,
      on_failure,
      user,
    );
  }

  late final _lw_pc_create_answerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<lw_pc_t>,
              lw_sdp_success_cb,
              lw_sdp_failure_cb,
              ffi.Pointer<ffi.Void>)>>('lw_pc_create_answer');
  late final _lw_pc_create_answer = _lw_pc_create_answerPtr.asFunction<
      void Function(ffi.Pointer<lw_pc_t>, lw_sdp_success_cb, lw_sdp_failure_cb,
          ffi.Pointer<ffi.Void>)>();

  /// Applies a local/remote session description. `type` is "offer"/"answer".
  void lw_pc_set_local_description(
    ffi.Pointer<lw_pc_t> pc,
    ffi.Pointer<ffi.Char> sdp,
    ffi.Pointer<ffi.Char> type,
    lw_set_sdp_success_cb on_success,
    lw_sdp_failure_cb on_failure,
    ffi.Pointer<ffi.Void> user,
  ) {
    return _lw_pc_set_local_description(
      pc,
      sdp,
      type,
      on_success,
      on_failure,
      user,
    );
  }

  late final _lw_pc_set_local_descriptionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<lw_pc_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              lw_set_sdp_success_cb,
              lw_sdp_failure_cb,
              ffi.Pointer<ffi.Void>)>>('lw_pc_set_local_description');
  late final _lw_pc_set_local_description =
      _lw_pc_set_local_descriptionPtr.asFunction<
          void Function(
              ffi.Pointer<lw_pc_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              lw_set_sdp_success_cb,
              lw_sdp_failure_cb,
              ffi.Pointer<ffi.Void>)>();

  void lw_pc_set_remote_description(
    ffi.Pointer<lw_pc_t> pc,
    ffi.Pointer<ffi.Char> sdp,
    ffi.Pointer<ffi.Char> type,
    lw_set_sdp_success_cb on_success,
    lw_sdp_failure_cb on_failure,
    ffi.Pointer<ffi.Void> user,
  ) {
    return _lw_pc_set_remote_description(
      pc,
      sdp,
      type,
      on_success,
      on_failure,
      user,
    );
  }

  late final _lw_pc_set_remote_descriptionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<lw_pc_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              lw_set_sdp_success_cb,
              lw_sdp_failure_cb,
              ffi.Pointer<ffi.Void>)>>('lw_pc_set_remote_description');
  late final _lw_pc_set_remote_description =
      _lw_pc_set_remote_descriptionPtr.asFunction<
          void Function(
              ffi.Pointer<lw_pc_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>,
              lw_set_sdp_success_cb,
              lw_sdp_failure_cb,
              ffi.Pointer<ffi.Void>)>();

  /// Adds a remote ICE candidate.
  void lw_pc_add_ice_candidate(
    ffi.Pointer<lw_pc_t> pc,
    ffi.Pointer<ffi.Char> mid,
    int mline_index,
    ffi.Pointer<ffi.Char> candidate,
  ) {
    return _lw_pc_add_ice_candidate(
      pc,
      mid,
      mline_index,
      candidate,
    );
  }

  late final _lw_pc_add_ice_candidatePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<lw_pc_t>, ffi.Pointer<ffi.Char>,
              ffi.Int, ffi.Pointer<ffi.Char>)>>('lw_pc_add_ice_candidate');
  late final _lw_pc_add_ice_candidate = _lw_pc_add_ice_candidatePtr.asFunction<
      void Function(ffi.Pointer<lw_pc_t>, ffi.Pointer<ffi.Char>, int,
          ffi.Pointer<ffi.Char>)>();

  void lw_pc_get_stats(
    ffi.Pointer<lw_pc_t> pc,
    lw_stats_success_cb on_success,
    lw_sdp_failure_cb on_failure,
    ffi.Pointer<ffi.Void> user,
  ) {
    return _lw_pc_get_stats(
      pc,
      on_success,
      on_failure,
      user,
    );
  }

  late final _lw_pc_get_statsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<lw_pc_t>, lw_stats_success_cb,
              lw_sdp_failure_cb, ffi.Pointer<ffi.Void>)>>('lw_pc_get_stats');
  late final _lw_pc_get_stats = _lw_pc_get_statsPtr.asFunction<
      void Function(ffi.Pointer<lw_pc_t>, lw_stats_success_cb,
          lw_sdp_failure_cb, ffi.Pointer<ffi.Void>)>();

  /// Opens a data channel. `label` must be non-NULL. Returns NULL on failure; the
  /// handle owns one reference.
  ffi.Pointer<lw_data_channel_t> lw_pc_create_data_channel(
    ffi.Pointer<lw_pc_t> pc,
    ffi.Pointer<ffi.Char> label,
    ffi.Pointer<LwDataChannelInit> init,
  ) {
    return _lw_pc_create_data_channel(
      pc,
      label,
      init,
    );
  }

  late final _lw_pc_create_data_channelPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<lw_data_channel_t> Function(
              ffi.Pointer<lw_pc_t>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<LwDataChannelInit>)>>('lw_pc_create_data_channel');
  late final _lw_pc_create_data_channel =
      _lw_pc_create_data_channelPtr.asFunction<
          ffi.Pointer<lw_data_channel_t> Function(ffi.Pointer<lw_pc_t>,
              ffi.Pointer<ffi.Char>, ffi.Pointer<LwDataChannelInit>)>();

  /// Sends one message. `binary` distinguishes a binary message from text, which
  /// the far side is told. Returns 0 on success, negative on error.
  ///
  /// Success means the message was accepted for sending, not that it arrived.
  /// Sending faster than the transport drains grows the buffered amount without
  /// bound, so a caller that can outrun the link should watch
  /// lw_data_channel_buffered_amount.
  int lw_data_channel_send(
    ffi.Pointer<lw_data_channel_t> channel,
    ffi.Pointer<ffi.Uint8> data,
    int size,
    int binary,
  ) {
    return _lw_data_channel_send(
      channel,
      data,
      size,
      binary,
    );
  }

  late final _lw_data_channel_sendPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<lw_data_channel_t>,
              ffi.Pointer<ffi.Uint8>,
              ffi.Uint32,
              ffi.Int)>>('lw_data_channel_send');
  late final _lw_data_channel_send = _lw_data_channel_sendPtr.asFunction<
      int Function(
          ffi.Pointer<lw_data_channel_t>, ffi.Pointer<ffi.Uint8>, int, int)>();

  /// Closes the channel. The handle stays valid until lw_release.
  void lw_data_channel_close(
    ffi.Pointer<lw_data_channel_t> channel,
  ) {
    return _lw_data_channel_close(
      channel,
    );
  }

  late final _lw_data_channel_closePtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<lw_data_channel_t>)>>(
      'lw_data_channel_close');
  late final _lw_data_channel_close = _lw_data_channel_closePtr
      .asFunction<void Function(ffi.Pointer<lw_data_channel_t>)>();

  /// The channel's id, or negative before one is assigned or on error.
  int lw_data_channel_id(
    ffi.Pointer<lw_data_channel_t> channel,
  ) {
    return _lw_data_channel_id(
      channel,
    );
  }

  late final _lw_data_channel_idPtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<lw_data_channel_t>)>>(
      'lw_data_channel_id');
  late final _lw_data_channel_id = _lw_data_channel_idPtr
      .asFunction<int Function(ffi.Pointer<lw_data_channel_t>)>();

  /// The channel's state as lw_data_channel_state, negative on error.
  int lw_data_channel_get_state(
    ffi.Pointer<lw_data_channel_t> channel,
  ) {
    return _lw_data_channel_get_state(
      channel,
    );
  }

  late final _lw_data_channel_get_statePtr = _lookup<
          ffi.NativeFunction<ffi.Int Function(ffi.Pointer<lw_data_channel_t>)>>(
      'lw_data_channel_get_state');
  late final _lw_data_channel_get_state = _lw_data_channel_get_statePtr
      .asFunction<int Function(ffi.Pointer<lw_data_channel_t>)>();

  /// Bytes accepted for sending but not yet handed to the transport.
  int lw_data_channel_buffered_amount(
    ffi.Pointer<lw_data_channel_t> channel,
  ) {
    return _lw_data_channel_buffered_amount(
      channel,
    );
  }

  late final _lw_data_channel_buffered_amountPtr = _lookup<
          ffi
          .NativeFunction<ffi.Uint64 Function(ffi.Pointer<lw_data_channel_t>)>>(
      'lw_data_channel_buffered_amount');
  late final _lw_data_channel_buffered_amount =
      _lw_data_channel_buffered_amountPtr
          .asFunction<int Function(ffi.Pointer<lw_data_channel_t>)>();

  /// The channel's label, owned by the caller (lw_string_free). NULL on error.
  ffi.Pointer<ffi.Char> lw_data_channel_label(
    ffi.Pointer<lw_data_channel_t> channel,
  ) {
    return _lw_data_channel_label(
      channel,
    );
  }

  late final _lw_data_channel_labelPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<lw_data_channel_t>)>>('lw_data_channel_label');
  late final _lw_data_channel_label = _lw_data_channel_labelPtr.asFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<lw_data_channel_t>)>();

  /// Registers `observer` for `channel`, replacing any previous one. Returns 0 on
  /// success, negative on error. Remove it before releasing the channel.
  int lw_data_channel_set_observer(
    ffi.Pointer<lw_data_channel_t> channel,
    ffi.Pointer<LwDataChannelObserver> observer,
    ffi.Pointer<ffi.Void> user,
  ) {
    return _lw_data_channel_set_observer(
      channel,
      observer,
      user,
    );
  }

  late final _lw_data_channel_set_observerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<lw_data_channel_t>,
              ffi.Pointer<LwDataChannelObserver>,
              ffi.Pointer<ffi.Void>)>>('lw_data_channel_set_observer');
  late final _lw_data_channel_set_observer =
      _lw_data_channel_set_observerPtr.asFunction<
          int Function(ffi.Pointer<lw_data_channel_t>,
              ffi.Pointer<LwDataChannelObserver>, ffi.Pointer<ffi.Void>)>();

  /// Removes and destroys the channel's observer, if any.
  void lw_data_channel_remove_observer(
    ffi.Pointer<lw_data_channel_t> channel,
  ) {
    return _lw_data_channel_remove_observer(
      channel,
    );
  }

  late final _lw_data_channel_remove_observerPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<lw_data_channel_t>)>>(
      'lw_data_channel_remove_observer');
  late final _lw_data_channel_remove_observer =
      _lw_data_channel_remove_observerPtr
          .asFunction<void Function(ffi.Pointer<lw_data_channel_t>)>();

  /// Registers `observer` for `pc`, replacing any previous one. Returns 0 on
  /// success, negative on error. Remove it (or before releasing the pc) with
  /// lw_pc_remove_observer.
  int lw_pc_set_observer(
    ffi.Pointer<lw_pc_t> pc,
    ffi.Pointer<LwPcObserver> observer,
    ffi.Pointer<ffi.Void> user,
  ) {
    return _lw_pc_set_observer(
      pc,
      observer,
      user,
    );
  }

  late final _lw_pc_set_observerPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<lw_pc_t>, ffi.Pointer<LwPcObserver>,
              ffi.Pointer<ffi.Void>)>>('lw_pc_set_observer');
  late final _lw_pc_set_observer = _lw_pc_set_observerPtr.asFunction<
      int Function(ffi.Pointer<lw_pc_t>, ffi.Pointer<LwPcObserver>,
          ffi.Pointer<ffi.Void>)>();

  /// Removes and destroys the pc's observer, if any.
  void lw_pc_remove_observer(
    ffi.Pointer<lw_pc_t> pc,
  ) {
    return _lw_pc_remove_observer(
      pc,
    );
  }

  late final _lw_pc_remove_observerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<lw_pc_t>)>>(
          'lw_pc_remove_observer');
  late final _lw_pc_remove_observer = _lw_pc_remove_observerPtr
      .asFunction<void Function(ffi.Pointer<lw_pc_t>)>();
}

/// One plane of a dmabuf-backed frame.
///
/// fd is NON-OWNING: owned by the producer (the decoder CAPTURE-queue pool).
/// It is valid only until the matching LwFrameRelease is invoked, and only
/// within a single pool_generation (the kernel reuses fd numbers after a
/// pool is torn down). Consumers MUST NOT close fd.
final class LwDmabufPlane extends ffi.Struct {
  /// non-owning; valid until release_cb
  @ffi.Int32()
  external int fd;

  /// byte offset of this plane within the dmabuf
  @ffi.Uint32()
  external int offset;

  /// row stride in bytes
  @ffi.Uint32()
  external int pitch;
}

/// A decoded frame, described by reference (zero copy).
///
/// `size` is sizeof(LwDmabufDescriptor) at the producer's compile time. A
/// consumer built against a different ABI minor MUST check `desc->size`
/// before reading any field beyond it: read min(sizeof(local), desc->size)
/// bytes, treat the remainder as absent. New fields only ever append.
///
/// `num_planes` is attacker/bug-reachable via the bitstream path upstream;
/// consumers MUST validate `num_planes <= LW_MAX_PLANES` before indexing
/// planes[] rather than trusting it.
final class LwDmabufDescriptor extends ffi.Struct {
  /// sizeof(LwDmabufDescriptor)
  @ffi.Uint32()
  external int size;

  /// DRM_FORMAT_*
  @ffi.Uint32()
  external int fourcc;

  /// DRM_FORMAT_MOD_* (AFBC/UBWC/linear)
  @ffi.Uint64()
  external int modifier;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  /// 1..LW_MAX_PLANES; validate before indexing
  @ffi.Uint32()
  external int num_planes;

  @ffi.Array.multi([4])
  external ffi.Array<LwDmabufPlane> planes;

  /// -1 none; non-owning. Normally -1: DQBUF
  /// implies decode complete. Reserved for
  /// future GPU-producer paths.
  @ffi.Int32()
  external int acquire_fence_fd;

  /// 0/90/180/270; RTP CVO passthrough
  @ffi.Uint32()
  external int rotation;

  /// for A/V sync + latency HUD
  @ffi.Int64()
  external int rtp_timestamp_us;

  /// monotonic within a session
  @ffi.Uint64()
  external int frame_seq;

  /// increments on pool reallocation; fd numbers
  /// are unique/stable only WITHIN a generation
  /// (kernel reuses fd values after pool close).
  /// Consumers key import caches on this.
  @ffi.Uint32()
  external int pool_generation;

  /// buffers in the producer's pool, or 0 if the
  /// producer does not know. A consumer that holds
  /// frames MUST bound what it holds against this:
  /// hold too many and the producer starves waiting
  /// for a buffer to decode into. Pools differ by an
  /// order of magnitude -- a VAAPI surface pool runs
  /// to dozens, a V4L2 CAPTURE pool is often reorder
  /// depth plus pipeline plus one, so eight to ten --
  /// which is why a consumer cannot pick a fixed
  /// depth that suits both. Treat 0 as small.
  @ffi.Uint32()
  external int pool_size;
}

/// The sink callback table. Registered with the sink registry and bound to a
/// track by token.
///
/// `size` is sizeof(LwVideoSinkV1): forward-compat gate for appended fields.
/// When the function shape must change, introduce LwVideoSinkV2.
final class LwVideoSinkV1 extends ffi.Struct {
  /// sizeof(LwVideoSinkV1)
  @ffi.Uint32()
  external int size;

  /// Called on the DECODER DELIVERY THREAD. MUST be non-blocking and
  /// allocation-free (do an SPSC POD handoff of desc + release pair).
  ///
  /// Consumer either:
  /// - TAKES the frame: stores `desc` BY VALUE, stores
  /// `release`+`release_ctx`, returns NONZERO. It now owns exactly one release
  /// obligation and MUST call `release(release_ctx)` exactly once.
  /// - DECLINES: returns 0. The producer releases the frame immediately
  /// (latest-wins drop). Declining is THE drop mechanism — it keeps the
  /// decoder unblocked; decode never stalls on presentation.
  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<LwDmabufDescriptor> desc,
              LwFrameRelease release,
              ffi.Pointer<ffi.Void> release_ctx,
              ffi.Pointer<ffi.Void> user)>> on_frame;

  /// Announces the format/geometry of the generation that is about to begin.
  /// ALWAYS precedes the first on_frame of a new pool_generation.
  /// NORMATIVE: on this call the consumer MUST invalidate all cached imports
  /// from prior generations — fd numbers may be reused by the kernel across
  /// pool reallocation and are NOT identity. `fmt_only` carries a valid
  /// descriptor with no live fds to import.
  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<LwDmabufDescriptor> fmt_only,
              ffi.Pointer<ffi.Void> user)>> on_format;

  /// End of stream. No further on_frame for this binding.
  external ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> user)>> on_eos;
}

/// Invoked by the consumer exactly once when it is done with a taken frame
/// (scanout out-fence signaled / wl_buffer.release). Maps to producer
/// re-QBUF. release_ctx is the cookie the producer handed to on_frame.
typedef LwFrameRelease
    = ffi.Pointer<ffi.NativeFunction<LwFrameReleaseFunction>>;
typedef LwFrameReleaseFunction = ffi.Void Function(
    ffi.Pointer<ffi.Void> release_ctx);
typedef DartLwFrameReleaseFunction = void Function(
    ffi.Pointer<ffi.Void> release_ctx);

final class lw_factory extends ffi.Opaque {}

/// Opaque handle to a peer-connection factory.
typedef lw_factory_t = lw_factory;

final class lw_video_track extends ffi.Opaque {}

/// Unguessable, nonzero handle to a registered video sink. 0 is invalid.
typedef lw_video_sink_token = ffi.Uint64;
typedef Dartlw_video_sink_token = int;

/// Opaque handle to a video track, produced by the control-plane shim.
typedef lw_video_track_t = lw_video_track;

/// Per-decoded-frame callback (fires on the decoder delivery thread) reporting
/// the frame's pixel dimensions. For counting/telemetry only -- the frame
/// itself never crosses here (native frames flow through the sink registry).
/// Must return promptly and must not re-enter the track API (it runs on the
/// delivery path). Pass cb = NULL to clear.
typedef lw_frame_cb = ffi.Pointer<ffi.NativeFunction<lw_frame_cbFunction>>;
typedef lw_frame_cbFunction = ffi.Void Function(
    ffi.Int width, ffi.Int height, ffi.Pointer<ffi.Void> user);
typedef Dartlw_frame_cbFunction = void Function(
    int width, int height, ffi.Pointer<ffi.Void> user);

final class lw_pc extends ffi.Opaque {}

final class lw_transceiver extends ffi.Opaque {}

final class lw_receiver extends ffi.Opaque {}

/// Media kind for a transceiver.
enum lw_media_type {
  LW_MEDIA_AUDIO(0),
  LW_MEDIA_VIDEO(1),
  LW_MEDIA_DATA(2);

  final int value;
  const lw_media_type(this.value);

  static lw_media_type fromValue(int value) => switch (value) {
        0 => LW_MEDIA_AUDIO,
        1 => LW_MEDIA_VIDEO,
        2 => LW_MEDIA_DATA,
        _ => throw ArgumentError("Unknown value for lw_media_type: $value"),
      };
}

/// Opaque handles produced by the calls below.
typedef lw_pc_t = lw_pc;
typedef lw_transceiver_t = lw_transceiver;
typedef lw_receiver_t = lw_receiver;

final class lw_video_source extends ffi.Opaque {}

final class lw_sender extends ffi.Opaque {}

/// Opaque handles for the send side.
typedef lw_video_source_t = lw_video_source;
typedef lw_sender_t = lw_sender;

/// Per-track frame counters, cheap enough to read every frame: they are plain
/// counters, read without taking the lock the delivery path holds.
///
/// These describe the local pipeline -- what the decoder produced and where it
/// went. They say nothing about the network; RTP, RTCP, ICE and DTLS statistics
/// are gathered asynchronously by the library and are a separate request.
///
/// Rates are deliberately absent. Two samples and the elapsed time between them
/// give a rate over whatever window the caller wants, where a rate computed
/// here would impose one.
final class LwVideoTrackStats extends ffi.Struct {
  /// sizeof(LwVideoTrackStats)
  @ffi.Uint32()
  external int size;

  @ffi.Uint32()
  external int reserved;

  /// Every decoded frame the track delivered, whatever path it then took.
  @ffi.Uint64()
  external int frames_delivered;

  /// Delivered as a dmabuf to a bound sink, which the sink took.
  @ffi.Uint64()
  external int frames_native;

  /// Delivered through the software path: no native buffer, so the frame was
  /// converted. Nonzero means the zero-copy path is not in use.
  @ffi.Uint64()
  external int frames_cpu;

  /// Native frames that reached no sink: none bound, the sink declined, or the
  /// buffer was some other implementation's native type.
  @ffi.Uint64()
  external int frames_dropped;

  /// Geometry of the most recent frame, or 0 before the first.
  @ffi.Uint32()
  external int last_width;

  @ffi.Uint32()
  external int last_height;

  /// CLOCK_MONOTONIC microseconds at the most recent frame, or 0 before the
  /// first. Paired with frames_delivered across two calls, this gives a rate.
  @ffi.Int64()
  external int last_frame_us;
}

/// Completion callbacks for the async SDP operations below. They are invoked on
/// the signaling thread. `user` is the opaque cookie passed to the originating
/// call.
///
/// String payloads are owned by the callback and stay valid after it returns,
/// so a consumer that has to hand the payload to another thread before reading
/// it can do so; retire each with lw_string_free. Nothing is allocated for a
/// NULL callback. A payload may be NULL if it could not be allocated.
typedef lw_sdp_success_cb
    = ffi.Pointer<ffi.NativeFunction<lw_sdp_success_cbFunction>>;
typedef lw_sdp_success_cbFunction = ffi.Void Function(ffi.Pointer<ffi.Char> sdp,
    ffi.Pointer<ffi.Char> type, ffi.Pointer<ffi.Void> user);
typedef Dartlw_sdp_success_cbFunction = void Function(ffi.Pointer<ffi.Char> sdp,
    ffi.Pointer<ffi.Char> type, ffi.Pointer<ffi.Void> user);
typedef lw_sdp_failure_cb
    = ffi.Pointer<ffi.NativeFunction<lw_sdp_failure_cbFunction>>;
typedef lw_sdp_failure_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Char> error, ffi.Pointer<ffi.Void> user);
typedef Dartlw_sdp_failure_cbFunction = void Function(
    ffi.Pointer<ffi.Char> error, ffi.Pointer<ffi.Void> user);
typedef lw_set_sdp_success_cb
    = ffi.Pointer<ffi.NativeFunction<lw_set_sdp_success_cbFunction>>;
typedef lw_set_sdp_success_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Void> user);
typedef Dartlw_set_sdp_success_cbFunction = void Function(
    ffi.Pointer<ffi.Void> user);

/// Statistics the library gathers from the transport: RTP, RTCP, ICE and DTLS.
///
/// Delivered as a JSON array, one object per report, each carrying its own id,
/// type and timestamp along with its members -- the shape the library already
/// produces, rather than a C mirror of its sixteen member types.
///
/// Asynchronous because that is how the library collects them. A synchronous
/// call would either block one of its threads or hand back something stale.
///
/// Poll these at human rates, a second or so apart. The per-frame pipeline
/// counters above are the ones to read at frame rate; these allocate and
/// serialize on the signaling thread.
///
/// The document is owned by the callback, as the SDP payloads are, and is
/// retired with lw_string_free.
typedef lw_stats_success_cb
    = ffi.Pointer<ffi.NativeFunction<lw_stats_success_cbFunction>>;
typedef lw_stats_success_cbFunction = ffi.Void Function(
    ffi.Pointer<ffi.Char> json, ffi.Pointer<ffi.Void> user);
typedef Dartlw_stats_success_cbFunction = void Function(
    ffi.Pointer<ffi.Char> json, ffi.Pointer<ffi.Void> user);

final class lw_data_channel extends ffi.Opaque {}

enum lw_data_channel_state {
  LW_DATA_CHANNEL_CONNECTING(0),
  LW_DATA_CHANNEL_OPEN(1),
  LW_DATA_CHANNEL_CLOSING(2),
  LW_DATA_CHANNEL_CLOSED(3);

  final int value;
  const lw_data_channel_state(this.value);

  static lw_data_channel_state fromValue(int value) => switch (value) {
        0 => LW_DATA_CHANNEL_CONNECTING,
        1 => LW_DATA_CHANNEL_OPEN,
        2 => LW_DATA_CHANNEL_CLOSING,
        3 => LW_DATA_CHANNEL_CLOSED,
        _ => throw ArgumentError(
            "Unknown value for lw_data_channel_state: $value"),
      };
}

/// Channel configuration. Pass NULL to lw_pc_create_data_channel for the
/// defaults: ordered and reliable, which is what most callers want.
///
/// max_retransmit_time_ms and max_retransmits are the two ways to make a
/// channel unreliable and are mutually exclusive; -1 leaves both unset.
final class LwDataChannelInit extends ffi.Struct {
  /// sizeof(LwDataChannelInit)
  @ffi.Uint32()
  external int size;

  /// nonzero: deliver in order (default)
  @ffi.Int32()
  external int ordered;

  /// -1 unset
  @ffi.Int32()
  external int max_retransmit_time_ms;

  /// -1 unset
  @ffi.Int32()
  external int max_retransmits;

  /// nonzero: agreed out of band, use `id`
  @ffi.Int32()
  external int negotiated;

  /// channel id when negotiated
  @ffi.Int32()
  external int id;
}

/// ---- Data channel -----------------------------------------------------
typedef lw_data_channel_t = lw_data_channel;

/// Channel events, invoked on the signaling thread. Any field may be NULL. The
/// struct is copied on registration; the function pointers and `user` must
/// remain valid until the observer is removed.
final class LwDataChannelObserver extends ffi.Struct {
  /// sizeof(LwDataChannelObserver)
  @ffi.Uint32()
  external int size;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int state, ffi.Pointer<ffi.Void> user)>>
      on_state;

  /// One message. `data` is owned by the callback (lw_string_free) and is
  /// `size` bytes, with a NUL appended past them.
  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Char> data, ffi.Uint32 size,
              ffi.Int binary, ffi.Pointer<ffi.Void> user)>> on_message;
}

/// State values delivered to the observer callbacks below. These mirror the
/// library's own RTC*State enums, which the shim static-asserts against, so a
/// consumer needs only this header.
enum lw_signaling_state {
  LW_SIGNALING_STABLE(0),
  LW_SIGNALING_HAVE_LOCAL_OFFER(1),
  LW_SIGNALING_HAVE_REMOTE_OFFER(2),
  LW_SIGNALING_HAVE_LOCAL_PRANSWER(3),
  LW_SIGNALING_HAVE_REMOTE_PRANSWER(4),
  LW_SIGNALING_CLOSED(5);

  final int value;
  const lw_signaling_state(this.value);

  static lw_signaling_state fromValue(int value) => switch (value) {
        0 => LW_SIGNALING_STABLE,
        1 => LW_SIGNALING_HAVE_LOCAL_OFFER,
        2 => LW_SIGNALING_HAVE_REMOTE_OFFER,
        3 => LW_SIGNALING_HAVE_LOCAL_PRANSWER,
        4 => LW_SIGNALING_HAVE_REMOTE_PRANSWER,
        5 => LW_SIGNALING_CLOSED,
        _ =>
          throw ArgumentError("Unknown value for lw_signaling_state: $value"),
      };
}

enum lw_pc_state {
  LW_PC_STATE_NEW(0),
  LW_PC_STATE_CONNECTING(1),
  LW_PC_STATE_CONNECTED(2),
  LW_PC_STATE_DISCONNECTED(3),
  LW_PC_STATE_FAILED(4),
  LW_PC_STATE_CLOSED(5);

  final int value;
  const lw_pc_state(this.value);

  static lw_pc_state fromValue(int value) => switch (value) {
        0 => LW_PC_STATE_NEW,
        1 => LW_PC_STATE_CONNECTING,
        2 => LW_PC_STATE_CONNECTED,
        3 => LW_PC_STATE_DISCONNECTED,
        4 => LW_PC_STATE_FAILED,
        5 => LW_PC_STATE_CLOSED,
        _ => throw ArgumentError("Unknown value for lw_pc_state: $value"),
      };
}

enum lw_ice_gathering_state {
  LW_ICE_GATHERING_NEW(0),
  LW_ICE_GATHERING_GATHERING(1),
  LW_ICE_GATHERING_COMPLETE(2);

  final int value;
  const lw_ice_gathering_state(this.value);

  static lw_ice_gathering_state fromValue(int value) => switch (value) {
        0 => LW_ICE_GATHERING_NEW,
        1 => LW_ICE_GATHERING_GATHERING,
        2 => LW_ICE_GATHERING_COMPLETE,
        _ => throw ArgumentError(
            "Unknown value for lw_ice_gathering_state: $value"),
      };
}

enum lw_ice_connection_state {
  LW_ICE_CONNECTION_NEW(0),
  LW_ICE_CONNECTION_CHECKING(1),
  LW_ICE_CONNECTION_COMPLETED(2),
  LW_ICE_CONNECTION_CONNECTED(3),
  LW_ICE_CONNECTION_FAILED(4),
  LW_ICE_CONNECTION_DISCONNECTED(5),
  LW_ICE_CONNECTION_CLOSED(6);

  final int value;
  const lw_ice_connection_state(this.value);

  static lw_ice_connection_state fromValue(int value) => switch (value) {
        0 => LW_ICE_CONNECTION_NEW,
        1 => LW_ICE_CONNECTION_CHECKING,
        2 => LW_ICE_CONNECTION_COMPLETED,
        3 => LW_ICE_CONNECTION_CONNECTED,
        4 => LW_ICE_CONNECTION_FAILED,
        5 => LW_ICE_CONNECTION_DISCONNECTED,
        6 => LW_ICE_CONNECTION_CLOSED,
        _ => throw ArgumentError(
            "Unknown value for lw_ice_connection_state: $value"),
      };
}

/// Per-event C callbacks, invoked on the signaling thread. Any field may be
/// NULL. State ints take the values of the enums above. The
/// struct is copied on registration, so it need not outlive the call; the
/// function pointers and `user` must remain valid until the observer is
/// removed.
final class LwPcObserver extends ffi.Struct {
  /// sizeof(LwPcObserver)
  @ffi.Uint32()
  external int size;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int state, ffi.Pointer<ffi.Void> user)>>
      on_signaling_state;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int state, ffi.Pointer<ffi.Void> user)>>
      on_connection_state;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int state, ffi.Pointer<ffi.Void> user)>>
      on_ice_gathering_state;

  external ffi.Pointer<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int state, ffi.Pointer<ffi.Void> user)>>
      on_ice_connection_state;

  /// A local ICE candidate was gathered. The strings are owned by the callback
  /// (lw_string_free), as for the SDP callbacks above.
  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.Char> candidate,
              ffi.Pointer<ffi.Char> sdp_mid,
              ffi.Int sdp_mline_index,
              ffi.Pointer<ffi.Void> user)>> on_ice_candidate;

  external ffi.Pointer<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> user)>>
      on_renegotiation_needed;

  /// A remote track arrived. `transceiver` is an OWNING handle: retire it with
  /// lw_release; reach its receiver/video track via the transceiver
  /// accessors.
  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<lw_transceiver_t> transceiver,
              ffi.Pointer<ffi.Void> user)>> on_track;

  /// The far side opened a data channel. `channel` is an OWNING handle: retire
  /// it with lw_release. Register an observer on it to receive messages.
  external ffi.Pointer<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<lw_data_channel_t> channel,
              ffi.Pointer<ffi.Void> user)>> on_data_channel;
}

const int LW_ABI_VERSION = 7;

const int LW_MAX_PLANES = 4;
